#!/usr/bin/env python3
import sys


def solve(N: int, a: "List[int]", b: "List[int]", c: "List[int]"):
    a_pre = a[0] # 直前にaを選択した時の最大値
    b_pre = b[0] # 直前にbを選択した時の最大値
    c_pre = c[0] # 直前にcを選択した時の最大値

    a_cur = a[0] # aを選択した時の最大値
    b_cur = b[0] # bを選択した時の最大値
    c_cur = c[0] # cを選択した時の最大値

    for i in range(1, N):
        a_cur = a[i] + max(b_pre, c_pre)
        b_cur = b[i] + max(a_pre, c_pre)
        c_cur = c[i] + max(a_pre, b_pre)

        # 直前の値を更新
        a_pre, b_pre, c_pre = a_cur, b_cur, c_cur

    print(max(a_cur, b_cur, c_cur))

    return


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    a = [int()] * (N)  # type: "List[int]"
    b = [int()] * (N)  # type: "List[int]"
    c = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
        c[i] = int(next(tokens))
    solve(N, a, b, c)

if __name__ == '__main__':
    main()
