#!/usr/bin/env python3
import sys

from jinja2.nodes import List


def solve(N: int, A: "List[int]"):
    if N < 4:
        print(N)
        return

    stack = []
    for number in range(N):
        stack.append(A[number])
        if len(stack) >= 4 and stack[-4] == stack[-3] == stack[-2] == stack[-1]:
            for _ in range(4):
                stack.pop()

    print(len(stack))
    return

def solve2(N: int, A: "List[int]"):
    if N < 4:
        print(N)
        return

    number = 0
    while number < N - 3:
        if number +  1 >= len(A): break

        if A[number] == A[number + 1] == A[number + 2] == A[number + 3]:
            del A[number : number + 4]
            number -= 3 if number >= 3 else 0
            continue

        number += 1

    print(len(A))
    return


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve2(N, A)

if __name__ == '__main__':
    main()
