#!/usr/bin/env python3
import math
import sys


def solve(N: int, W: int, w: "List[int]", v: "List[int]"):
    # dp[i][sum_v] はi+1番目までの品物から価値がsum_vとなるように選んだときの、重さの総和の最小値
    dp = [[math.inf] * (sum(v) + 1) for _ in range(N+1)]
    dp[0][0] = 0

    for i in range(N):
        for j in range(0, sum(v)+1):
            if j >= v[i]: dp[i+1][j] = min(dp[i+1][j], dp[i][j - v[i]] + w[i])
            dp[i+1][j] = min(dp[i+1][j], dp[i][j])

    max_value = 0
    for j in range(0, sum(v)+1):
        if dp[N][j] <= W:
            max_value = j

    print(max_value)
    return


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    w = [int()] * (N)  # type: "List[int]"
    v = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        w[i] = int(next(tokens))
        v[i] = int(next(tokens))
    solve(N, W, w, v)

if __name__ == '__main__':
    main()
