#!/usr/bin/env python3
import sys


def solve(M: int):
    result_list = []
    while M>0:
        if M <= 3**5:
            for i in range(0, 6):
                if M >= 3**(5-i):
                    M -= 3**(5-i)
                    result_list.append(5-i)
                    break
        else:
            for j in range(0, 6):
                if M >= 3**(10-j):
                    M -= 3**(10-j)
                    result_list.append(10-j)
                    break

    print(len(result_list))
    print(" ".join(map(str, result_list)))
    return


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    M = int(next(tokens))  # type: int
    solve(M)

if __name__ == '__main__':
    main()
