#!/usr/bin/env python3
import sys


def solve(s: str, t: str):
    s_leng = len(s)
    t_leng = len(t)

    # 文字の長さの計算
    len_dp = [[0] * (t_leng + 1) for _ in range(s_leng + 1)]
    for i in range(1, s_leng + 1):
        for j in range(1, t_leng + 1):
            if s[i-1] == t[j-1]:
                len_dp[i][j] = len_dp[i-1][j-1] + 1
            else:
                len_dp[i][j] = max(len_dp[i-1][j], len_dp[i][j-1])

    # 文字列の復元(後ろから辿る)
    ans = []
    i, j = s_leng, t_leng
    while i > 0 and j > 0:
        if s[i-1] == t[j-1]:
            ans.append(s[i-1])
            i -= 1
            j -= 1
        elif len_dp[i][j] == len_dp[i-1][j]:
            i -= 1
        else:
            j -= 1

    print(''.join(reversed(ans)))
    return


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    s = next(tokens)  # type: str
    t = next(tokens)  # type: str
    solve(s, t)

if __name__ == '__main__':
    main()
