#!/usr/bin/env python3
import sys


def solve(N: int, A: "List[int]", B: "List[int]", C: "List[int]"):
    dp = [[0] * 3 for _ in range(N)]
    dp[0][0] = A[0]
    dp[0][1] = dp[0][0]
    dp[0][2] = dp[0][1]

    for number in range(1, N):
        dp[number][0] = dp[number-1][0] + A[number]

        dp[number][1] = max(dp[number-1][0], dp[number-1][1]) + B[number]

        if number == 1:
            dp[1][2] = dp[1][1]
            continue
        dp[number][2] = max(dp[number-1][1], dp[number-1][2]) + C[number]

    print(dp[N-1][2])
    return

# やっていることはsolve↑と同じ。こっちの方がメモリが
def solve2(N: int, A: "List[int]", B: "List[int]", C: "List[int]"):
    a_prev = A[0]
    b_prev = a_prev

    a = a_prev
    b = b_prev
    c = b

    for number in range(1, N):
        a_prev = a
        a = a_prev + A[number]

        b_prev = b
        b = max(a_prev, b_prev) + B[number]

        if number == 1:
            c = b
            continue
        c = max(c, b_prev) + C[number]

    print(c)
    return


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    B = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    C = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve2(N, A, B, C)

if __name__ == '__main__':
    main()
