#!/usr/bin/env python3
import math
import sys
from math import atan2

## なんか最後の2パターン(精度の問題？)が正解にならないがコミットする

def solve(N: int, Q: int, X: "List[int]", Y: "List[int]", A: "List[int]", B: "List[int]"):
    # モンスターの座標とindex番号のセットでリストを作る
    declination_list = [(0, (0, 0))] * N
    for i in range(N):
        # 精度を上げるため、最大公約数で正規化した座標を保存しておく
        gcd = math.gcd(abs(X[i]), abs(Y[i]))
        x_norm = X[i] // gcd
        y_norm = Y[i] // gcd
        declination_list[i] = (-atan2(y_norm, x_norm), x_norm, y_norm, i+1)

    # 偏角でソート
    declination_list.sort()

    # 同一偏角をグループにする
    group_list = []
    current_group = [declination_list[0]]
    for i in range(1, N):
        if declination_list[i - 1][1] == declination_list[i][1] and \
            declination_list[i - 1][2] == declination_list[i][2]:
            # 正規化した整数で比較
            current_group.append(declination_list[i])
        else:
            group_list.append(current_group)
            current_group = [declination_list[i]]
    group_list.append(current_group)

    # 何groupあるかカウントしておく
    group_count = len(group_list)

    # 結果用に累積和を作成
    group_cumsum = [0] * (group_count + 1)
    for i, group in enumerate(group_list):
        group_cumsum[i + 1] = group_cumsum[i] + len(group)

    # 何番目のindexがどのグループにいるかの逆引きリスト
    id_to_group_idx = {}
    for g_idx, group in enumerate(group_list):
        for coordinate in group:
            id_to_group_idx[coordinate[3]] = g_idx + 1

    # 計算
    for q in range(Q):
        start_target = id_to_group_idx[A[q]]
        end_target = id_to_group_idx[B[q]]

        # 結果を出力
        if start_target <= end_target:
            print(group_cumsum[end_target] - group_cumsum[start_target-1])
        else:
            print(group_cumsum[group_count] - group_cumsum[start_target-1] + group_cumsum[end_target])
    return


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word

    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    Q = int(next(tokens))  # type: int
    X = [int()] * (N)  # type: "List[int]"
    Y = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        X[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    A = [int()] * (Q)  # type: "List[int]"
    B = [int()] * (Q)  # type: "List[int]"
    for i in range(Q):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(N, Q, X, Y, A, B)


if __name__ == '__main__':
    main()
