#!/usr/bin/env python3
import sys
import math


def solve(N: int, K: int, h: "List[int]"):
    dp = [math.inf] * (N)  # 小さい値に更新していくので初期値はmath.infにしておく
    dp[0] = 0
    for i in range(N):
        for j in range(K):
            if i + j + 1 < N:
                cost = dp[i] + abs(h[i + j + 1] - h[i])
                if cost < dp[i + j + 1]:
                    dp[i + j + 1] = cost
    print(dp[N - 1])
    return


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    h = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, K, h)

if __name__ == '__main__':
    main()
