#!/usr/bin/env python3
import sys

sys.setrecursionlimit(10**6)

def solve(N: int, M: int, x: "List[int]", y: "List[int]"):
    # 1. 隣接リストの作成
    G = [[] for _ in range(N + 1)]
    for i in range(M):
        G[x[i]].append(y[i])

    # 2. メモ化用の配列
    # 初期値は0と区別して-1にする
    memo = [-1] * (N + 1)

    def get_length(v):
        # すでに計算済みならその値を返す
        if memo[v] != -1:
            return memo[v]

        res = 0
        for next_v in G[v]:
            # 行き先の頂点からの最長経路 + 1 と比較して最大値を更新
            res = max(res, get_length(next_v) + 1)

        # 結果をメモして返す
        memo[v] = res
        return res

    # 3. 全頂点をループして最大値を求める
    ans = 0
    for i in range(1, N + 1):
        ans = max(ans, get_length(i))

    print(ans)
    return


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    x = [int()] * (M)  # type: "List[int]"
    y = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        x[i] = int(next(tokens))
        y[i] = int(next(tokens))
    solve(N, M, x, y)

if __name__ == '__main__':
    main()
