#!/usr/bin/env python3
import sys
import math


def solve(N: int, h: "List[int]"):
    dp = [math.inf] * (N) # 小さい値に更新していくので初期値はmath.infにしておく
    dp[0] = 0
    for i in range(N):
        if i + 1 < N:
            cost = dp[i] + abs(h[i + 1] - h[i])
            if cost < dp[i + 1]:
                dp[i + 1] = cost
        if i + 2 < N:
            cost = dp[i] + abs(h[i + 2] - h[i])
            if cost < dp[i + 2]:
                dp[i + 2] = cost
    print(dp[N - 1])
    return


# Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    h = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, h)

if __name__ == '__main__':
    main()
